version: '3'
services:
  rabbitmq:
    container_name: rabbitmq_cont
    image: 'rabbitmq:3.6-management'
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "usr"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "8080:5672"
    labels:
      NAME: "rabbitmq"

  app:
    container_name: app_cont 
    build: . 
    ports:
    - "8082:8080"
